jboss-fuse/application-templates

quickstarts/jboss-fuse-camel-amq-template.json
quickstarts/jboss-fuse-camel-log-template.json
quickstarts/jboss-fuse-camel-rest-sql-template.json
quickstarts/jboss-fuse-cxf-rest-template.json

Changed icons, tags, versions, labels and descriptions to comply with OSFUSE-196-197 and other xpaas templates.

OSFUSE-196 OSFUSE-197

---

quickstarts/karaf2-camel-amq-template.json
quickstarts/karaf2-camel-log-template.json
quickstarts/karaf2-camel-rest-sql-template.json
quickstarts/karaf2-cxf-rest-template.json

@lburgazzoli @nicolaferraro @astefanutti @chirino Please merge

Fixes invalid JSON in quickstart templates

---

fis-image-streams.json

https://issues.jboss.org/browse/ENTESB-9917

ENTESB-9917 Commit changes that went into GA back into branch

---

fis-image-streams.json

https://issues.jboss.org/browse/ENTESB-9917

ENTESB-9917 Add changes that went into GA tag back into branch

---

fuse-apicurito.yml

seems this one can easily be out of sync, so remove for now
not sure if I'm targeting the right branch or not

ENTESB-9926 - remove version from label message

---

quickstarts/spring-boot-camel-amq-template.json

DO NOT MERGE
needs https://github.com/fabric8-quickstarts/spring-boot-camel-amq/pull/154 first, thanks!

[ENTESB-10178] Update spring-boot-camel-amq-template

---

fis-console-cluster-template.json
fis-console-namespace-template.json

@astefanutti Please help me test this change

ENTESB-10754 Update Fuse console on OpenShift with new branding

---

fuse-prometheus-operator.yml

I'll cherry-pick this fix to 7.5 branch after it's merged to master.

fix: ENTESB-11920 [ER1][OCP4] Prometheus installation doesn't work

---

fis-image-streams.json

Add back 7.4 image streams (#84)

---

fis-image-streams.json

Update fis-image-streams for 7.7

---

fis-image-streams.json

Adding 1.6 image streams for apicurio

ENTESB-13620 Add 1.6 image streams for apicurio

---

quickstarts/spring-boot-2-camel-soap-rest-bridge-template.json

Add soap rest bridge quickstart template

Add soap-rest-bridge template

---

README.md
fuse-console-cluster-rbac.yml
fuse-console-namespace-rbac.yml

Requires jboss-fuse/fuse-console-openshift#4.

ENTESB-8065: RBAC support for the Fuse console

---

fis-console-cluster-template.json
fis-console-namespace-template.json
fis-image-streams.json
fuse-apicurito.yml
fuse-console-cluster-os4.json
fuse-console-namespace-os4.json
quickstarts/eap-camel-amq-template.json
quickstarts/eap-camel-cdi-template.json
quickstarts/eap-camel-cxf-jaxrs-template.json
quickstarts/eap-camel-cxf-jaxws-template.json
quickstarts/eap-camel-jpa-template.json
quickstarts/karaf-camel-amq-template.json
quickstarts/karaf-camel-log-template.json
quickstarts/karaf-camel-rest-sql-template.json
quickstarts/karaf-cxf-rest-template.json
quickstarts/spring-boot-camel-amq-template.json
quickstarts/spring-boot-camel-config-template.json
quickstarts/spring-boot-camel-drools-template.json
quickstarts/spring-boot-camel-infinispan-template.json
quickstarts/spring-boot-camel-rest-3scale-template.json
quickstarts/spring-boot-camel-rest-sql-template.json
quickstarts/spring-boot-camel-teiid-template.json
quickstarts/spring-boot-camel-template.json
quickstarts/spring-boot-camel-xa-template.json
quickstarts/spring-boot-camel-xml-template.json
quickstarts/spring-boot-cxf-jaxrs-template.json
quickstarts/spring-boot-cxf-jaxws-template.json

ENTESB-13821 Change application-templates to use 1.7 versions

ENTESB-13821 Change application-templates to use 1.7 versions

---

update-fuse-version.sh

Issue: https://issues.redhat.com/browse/ENTESB-12695
I've enhanced the script to generate new image streams in fis-image-streams.json file for:
fuse-java-openshift
fuse-karaf-openshift
fuse-eap-openshift
fuse-console
fuse-apicurito
fuse-apicurito-generator

[ENTESB-12695] Generating new image streams

---

prometheus/prometheus-config.yml

Add the prometheus-config.yml; we need a place to store this and fabric8io-images/s2i is being deprecated

Add the prometheus-config.yml; we need a place to store this and fabric8io-images/s2i is being deprecated

---

monitoring/dashboards.md
monitoring/fuse-grafana-dashboard-routes-standalone.json
monitoring/fuse-grafana-dashboard-standalone.json
monitoring/fuse-grafana-dashboard.yml

https://issues.redhat.com/browse/ENTESB-14561

ENTESB-14561 - Default Grafana dashboards for Fuse - dashboard examples for standalone

---

fis-console-cluster-template.json
fis-console-namespace-template.json
fuse-apicurito.yml
fuse-console-cluster-os4.json
fuse-console-cluster-rbac.yml
fuse-console-namespace-os4.json
fuse-console-namespace-rbac.yml
quickstarts/eap-camel-amq-template.json
quickstarts/eap-camel-cdi-template.json
quickstarts/eap-camel-cxf-jaxrs-template.json
quickstarts/eap-camel-cxf-jaxws-template.json
quickstarts/eap-camel-jpa-template.json
quickstarts/karaf-camel-amq-template.json
quickstarts/karaf-camel-log-template.json
quickstarts/karaf-camel-rest-sql-template.json
quickstarts/karaf-cxf-rest-template.json
quickstarts/spring-boot-camel-amq-template.json
quickstarts/spring-boot-camel-config-template.json
quickstarts/spring-boot-camel-drools-template.json
quickstarts/spring-boot-camel-infinispan-template.json
quickstarts/spring-boot-camel-rest-3scale-template.json
quickstarts/spring-boot-camel-rest-sql-template.json
quickstarts/spring-boot-camel-teiid-template.json
quickstarts/spring-boot-camel-template.json
quickstarts/spring-boot-camel-xml-template.json
quickstarts/spring-boot-cxf-jaxrs-template.json
quickstarts/spring-boot-cxf-jaxws-template.json
update-fuse-version.sh

Issue: https://issues.redhat.com/browse/ENTESB-14400
See the JIRA issue for details

[ENTESB-14400] Provide metering labels for Fuse on Openshift resources

---

quickstarts/spring-boot-2-camel-amq-template.json
quickstarts/spring-boot-2-camel-config-template.json
quickstarts/spring-boot-2-camel-drools-template.json
quickstarts/spring-boot-2-camel-infinispan-template.json
quickstarts/spring-boot-2-camel-rest-3scale-template.json
quickstarts/spring-boot-2-camel-rest-sql-template.json
quickstarts/spring-boot-2-camel-soap-rest-bridge-template.json
quickstarts/spring-boot-2-camel-template.json
quickstarts/spring-boot-2-camel-xa-template.json
quickstarts/spring-boot-2-camel-xml-template.json
quickstarts/spring-boot-2-cxf-jaxrs-template.json
quickstarts/spring-boot-2-cxf-jaxrs-xml-template.json
quickstarts/spring-boot-2-cxf-jaxws-template.json
quickstarts/spring-boot-2-cxf-jaxws-xml-template.json

Issue: https://issues.redhat.com/browse/ENTESB-14400
Backport of https://github.com/jboss-fuse/application-templates/pull/150

[ENTESB-14400] Provide metering labels for Fuse on Openshift

---

fuse-apicurito.yml

Issue: https://issues.redhat.com/browse/ENTESB-15238

[ENTESB-15238][Apicurito] Wrong label syntax in fuse-apicurito.yml

---

monitoring/prometheusalerts.md
monitoring/prometheusalerts.yml

Added more metrics requested by QE

ENTESB-13780 Add alerts for metrics mentioned in issue

---

prometheus/prometheus-config.yml

Adding missing OldestInflightExchange metric

Add OldestInflightDuration metric

---

fis-console-cluster-template.json
fis-console-namespace-template.json
fis-image-streams.json
fuse-console-cluster-os4.json
fuse-console-namespace-os4.json
quickstarts/eap-camel-amq-template.json
quickstarts/eap-camel-cdi-template.json
quickstarts/eap-camel-cxf-jaxrs-template.json
quickstarts/eap-camel-cxf-jaxws-template.json
quickstarts/eap-camel-jpa-template.json
quickstarts/karaf-camel-amq-template.json
quickstarts/karaf-camel-log-template.json
quickstarts/karaf-camel-rest-sql-template.json
quickstarts/karaf-cxf-rest-template.json
quickstarts/spring-boot-2-camel-amq-template.json
quickstarts/spring-boot-2-camel-config-template.json
quickstarts/spring-boot-2-camel-drools-template.json
quickstarts/spring-boot-2-camel-infinispan-template.json
quickstarts/spring-boot-2-camel-rest-3scale-template.json
quickstarts/spring-boot-2-camel-rest-sql-template.json
quickstarts/spring-boot-2-camel-soap-rest-bridge-template.json
quickstarts/spring-boot-2-camel-template.json
quickstarts/spring-boot-2-camel-xa-template.json
quickstarts/spring-boot-2-camel-xml-template.json
quickstarts/spring-boot-2-cxf-jaxrs-template.json
quickstarts/spring-boot-2-cxf-jaxrs-xml-template.json
quickstarts/spring-boot-2-cxf-jaxws-template.json
quickstarts/spring-boot-2-cxf-jaxws-xml-template.json
update-fuse-version.sh

- Cherry picking over Radovan's commits of the upgrade-fuse-version script over to the sb2 branch (it was initially committed only to the sb1 branch)
- Ran the upgrade-fuse-version script to upgrade to 7.9

Upgrade application templates to 7.9

---

fis-console-namespace-template.json
fuse-apicurito.yml
fuse-console-cluster-os4.json
fuse-console-cluster-rbac.yml
fuse-console-namespace-os4.json
fuse-console-namespace-rbac.yml
quickstarts/eap-camel-amq-template.json
quickstarts/eap-camel-cdi-template.json
quickstarts/eap-camel-cxf-jaxrs-template.json
quickstarts/eap-camel-cxf-jaxws-template.json
quickstarts/eap-camel-jpa-template.json
quickstarts/karaf-camel-amq-template.json
quickstarts/karaf-camel-log-template.json
quickstarts/karaf-camel-rest-sql-template.json
quickstarts/karaf-cxf-rest-template.json
quickstarts/spring-boot-2-camel-amq-template.json
quickstarts/spring-boot-2-camel-config-template.json
quickstarts/spring-boot-2-camel-drools-template.json
quickstarts/spring-boot-2-camel-infinispan-template.json
quickstarts/spring-boot-2-camel-rest-3scale-template.json
quickstarts/spring-boot-2-camel-rest-sql-template.json
quickstarts/spring-boot-2-camel-soap-rest-bridge-template.json
quickstarts/spring-boot-2-camel-template.json
quickstarts/spring-boot-2-camel-xa-template.json
quickstarts/spring-boot-2-camel-xml-template.json
quickstarts/spring-boot-2-cxf-jaxrs-template.json
quickstarts/spring-boot-2-cxf-jaxrs-xml-template.json
quickstarts/spring-boot-2-cxf-jaxws-template.json
quickstarts/spring-boot-2-cxf-jaxws-xml-template.json

https://issues.redhat.com/browse/ENTESB-15704
Thanks !

Entesb 15704

---

quickstarts/spring-boot-2-camel-amq-template.json
quickstarts/spring-boot-2-camel-config-template.json
quickstarts/spring-boot-2-camel-drools-template.json
quickstarts/spring-boot-2-camel-infinispan-template.json
quickstarts/spring-boot-2-camel-rest-3scale-template.json
quickstarts/spring-boot-2-camel-rest-sql-template.json
quickstarts/spring-boot-2-camel-soap-rest-bridge-template.json
quickstarts/spring-boot-2-camel-template.json
quickstarts/spring-boot-2-camel-xml-template.json
quickstarts/spring-boot-2-cxf-jaxrs-template.json
quickstarts/spring-boot-2-cxf-jaxrs-xml-template.json
quickstarts/spring-boot-2-cxf-jaxws-template.json
quickstarts/spring-boot-2-cxf-jaxws-xml-template.json

Issue: https://issues.redhat.com/browse/ENTESB-15984

[ENTESB-15984] Quickstarts company metering labels are not created

---

quickstarts/karaf-camel-rhosak-template.json
quickstarts/spring-boot-2-camel-rhosak-template.json

Add templates for rhosak quickstarts, add to pom

Add rhosak templates

---

quickstarts/spring-boot-2-camel-rhosak-template.json

ENTESB-16928 Fix the git repo for the spring-boot-camel rhosak quickstart

ENTESB-16928 Fix the git repo for the spring-boot-camel rhosak quickstart

---

fis-image-streams.json

https://issues.redhat.com/browse/ENTESB-17158

ENTESB-17158 Fix image names in application-templates/fis-image-streams.json (2.1.x.sb2.redhat-7-x branch)

---

fis-image-streams.json

https://issues.redhat.com/browse/ENTESB-17158

ENTESB-17158 Fix image names in application-templates/fis-image-streams.json (2.1.x.sb2.redhat-7-9-x branch)

---

fis-image-streams.json
quickstarts/eap-camel-amq-template.json
quickstarts/eap-camel-cdi-template.json
quickstarts/eap-camel-cxf-jaxrs-template.json
quickstarts/eap-camel-cxf-jaxws-template.json
quickstarts/eap-camel-jpa-template.json
quickstarts/karaf-camel-amq-template.json
quickstarts/karaf-camel-log-template.json
quickstarts/karaf-camel-rest-sql-template.json
quickstarts/karaf-camel-rhosak-template.json
quickstarts/karaf-cxf-rest-template.json
quickstarts/spring-boot-2-camel-amq-template.json
quickstarts/spring-boot-2-camel-config-template.json
quickstarts/spring-boot-2-camel-drools-template.json
quickstarts/spring-boot-2-camel-infinispan-template.json
quickstarts/spring-boot-2-camel-rest-3scale-template.json
quickstarts/spring-boot-2-camel-rest-sql-template.json
quickstarts/spring-boot-2-camel-rhosak-template.json
quickstarts/spring-boot-2-camel-soap-rest-bridge-template.json
quickstarts/spring-boot-2-camel-template.json
quickstarts/spring-boot-2-camel-xa-template.json
quickstarts/spring-boot-2-camel-xml-template.json
quickstarts/spring-boot-2-cxf-jaxrs-template.json
quickstarts/spring-boot-2-cxf-jaxrs-xml-template.json
quickstarts/spring-boot-2-cxf-jaxws-template.json
quickstarts/spring-boot-2-cxf-jaxws-xml-template.json

Issue: https://issues.redhat.com/browse/ENTESB-18336

ENTESB-18336 Quickstarts have 1.10 version

---

quickstarts/spring-boot-2-camel-singleton-services-kubernetes.json

Fix GIT_REPO parameter default value.

ENTESB-18068: Provide camel "master" example for OpenShift

---

fis-console-cluster-template.json
fis-console-namespace-template.json
fuse-console-cluster-k8s.yml
fuse-console-cluster-os4.json
fuse-console-cluster-rbac.yml
fuse-console-namespace-k8s.yml
fuse-console-namespace-os4.json
fuse-console-namespace-rbac.yml

https://issues.redhat.com/browse/ENTESB-18903

ENTESB-18903 - Increase Hawtio's default memory limit to 512Mi
